#!/bin/sh
# Regenerate AGENTS.md from the repo's Cursor rule sources (single source of truth).
# Run after editing .cursor/rules/ai-guidelines.md or .cursor/rules/monorepo.md.
# Portable POSIX sh; produces deterministic, idempotent output.
set -eu

cd "$(dirname "$0")/.."

ai=.cursor/rules/ai-guidelines.md
mono=.cursor/rules/monorepo.md

for f in "$ai" "$mono"; do
  [ -f "$f" ] || { echo "missing source: $f" >&2; exit 1; }
done

{
  printf '<!-- GENERATED by scripts/sync-agents.sh from %s + %s. Do not edit directly; re-run this script after changing those files. -->\n' "$ai" "$mono"
  cat "$ai"
  printf '\n---\n\n'
  sed '1s/# TorrentSearch . Cursor Rules/# TorrentSearch — monorepo rules/' "$mono"
} > AGENTS.md

echo "regenerated: AGENTS.md (from $ai + $mono)"
